### ISSUE TITLE
Master Branch Protection

### ISSUE THREAD

**Issue by primetheus** [RohmingRobots/2017-2018-Code#19]
## Description
The _default_ branch of this repository is [**_master_**](https://github.com/RohmingRobots/2017-2018-code/tree/master), but it is not sufficiently protected. 

Protected branches ensure that collaborators on your repository cannot make irrevocable changes to branches. These branches can also be protected by requiring pull requests to have at least one approved review before they can be merged.

If you own a repository with multiple collaborators who create branches and open pull requests, you may need to [enforce branch protections](https://help.github.com/articles/configuring-protected-branches) to keep your project and pull requests organized and safe.

Protected branches block several features of Git on a branch that a repository administrator chooses to protect. A protected branch:

- Can't be force pushed
- Can't be deleted
- Can't have changes merged into it until [required status checks](https://help.github.com/articles/about-required-status-checks) pass
- Can't have changes merged into it until [required reviews are approved](https://help.github.com/articles/approving-a-pull-request-with-required-reviews)
- Can't be edited or have files uploaded to it from the web
- Can't have changes merged into it until changes to files that have a [designated code owner](https://help.github.com/articles/about-codeowners/) have been approved by that owner

## Task List
- [x] Protect the **_master_** branch
- [x] Require pull request reviews before merging
- [ ] Dismiss stale pull request approvals when new commits are pushed
- [ ] ~Require review from Code Owners~ (recommended if you have a project lead)
- [ ] Restrict who can dismiss pull request reviews (we normally don't want _anyone_ to bypass this check, as it encourages bad practice.)
- [ ] Require status checks to pass before merging
- [ ] Require branches to be up to date before merging
- [ ] Restrict who can push to this branch (we normally don't want _anyone_ to bypass this check either, for the same reason)
- [x] Include administrators (we should encourage administrators to be accountable to the team as well)
